spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ranjitkumarpalanisamy/microservices
          search-paths:
            - "ms-config-properties/{application}/{profile}"